name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

#    - name: Run tests
#      run: ./gradlew check test jacocoTestReport --stacktrace
#
#    - name: Send test results to CodeCov
#      run: bash <(curl -s https://codecov.io/bash)
